status = error
name = SparkLogConfig

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

rootLogger.level = WARN
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = console

# Silence the noisy ones
logger.wholetext.name = org.apache.spark.rdd.WholeTextFileRDD
logger.wholetext.level = WARN

logger.fileinput.name = org.apache.hadoop.mapreduce.lib.input.FileInputFormat
logger.fileinput.level = WARN
